version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    command: mongod --replSet rs0 --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017 # Map MongoDB's default port to the host


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
